- name: Configuring newly created EC2 instances
  hosts: all
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    environment_config:
      NODE_ENV: production
      ENVIRONMENT: production
      TYPEORM_CONNECTION: postgres
      TYPEORM_ENTITIES: /root/backend_app/modules/domain/**/*.entity.js
      TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
      
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for:
        timeout: 600 
  roles:
    - role: setup
      become: true
    - role: deploy_backend
      become: true
    - role: configure_node_exporter
      become: true